const ShopGoodsRouter = {
  route: null,
  name: null,
  title: '商品管理',
  type: 'folder',
  icon: 'iconfont icon-demo',
  filePath: 'views/ShopGoods/',
  order: null,
  inNav: true,
  children: [
    {
      title: '产品管理',
      type: 'folder',
      name: 'shopGoods',
      route: '/shop-goods/goods',
      filePath: 'plugins/ShopGoods/views/goods',
      inNav: true,
      icon: 'iconfont icon-demo',
      children: [
        {
          title: '产品列表',
          type: 'view',
          inNav: true,
          route: '/shop-goods/goods/list',
          icon: 'iconfont icon-add',
          name: 'shopGoodsList',
          filePath: 'plugins/ShopGoods/views/goods/GoodsList.vue',
          right: null,
        },
        {
          title: '产品编辑',
          type: 'view',
          inNav: true,
          route: '/shop-goods/goods/info',
          icon: 'iconfont icon-add',
          name: 'goodsInfo',
          filePath: 'plugins/ShopGoods/views/goods/GoodsInfo.vue',
          right: null,
        },
      ],
    },
    {
      title: '产品分组',
      type: 'view',
      name: 'GroupOps',
      route: '/shop-goods/group-ops',
      filePath: 'plugins/ShopGoods/views/group/GroupOps',
      inNav: true,
      icon: 'iconfont icon-demo',
      right: null,
    },
  ],
}

export default ShopGoodsRouter
